Watching for file changes with StatReloader
[30/Aug/2019 08:42:55] "GET /rango/ HTTP/1.1" 200 29
[30/Aug/2019 08:42:56] "GET /rango/ HTTP/1.1" 200 29
[30/Aug/2019 08:42:57] "GET /rango/ HTTP/1.1" 200 29
<<<<<<< HEAD
[30/Aug/2019 08:53:05] "GET /rango/ HTTP/1.1" 200 29
Not Found: /favicon.ico
[30/Aug/2019 08:53:06] "GET /favicon.ico HTTP/1.1" 404 2097
Not Found: /
[30/Aug/2019 09:17:21] "GET / HTTP/1.1" 404 2046
Not Found: /
[30/Aug/2019 09:32:10] "GET / HTTP/1.1" 404 2046
Not Found: /robots.txt
[30/Aug/2019 09:32:11] "GET /robots.txt HTTP/1.1" 404 2094
----------------------------------------
Exception happened during processing of request from ('82.221.105.7', 33512)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/dist-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/dist-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /sitemap.xml
[30/Aug/2019 09:32:12] "GET /sitemap.xml HTTP/1.1" 404 2097
Not Found: /.well-known/security.txt
[30/Aug/2019 09:32:12] "GET /.well-known/security.txt HTTP/1.1" 404 2136
----------------------------------------
Exception happened during processing of request from ('82.221.105.7', 33546)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/dist-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/dist-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /favicon.ico
[30/Aug/2019 09:32:13] "GET /favicon.ico HTTP/1.1" 404 2097
----------------------------------------
Exception happened during processing of request from ('82.221.105.7', 33621)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/dist-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/dist-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[30/Aug/2019 10:00:51] "GET / HTTP/1.1" 404 2046
Not Found: /http:/clientapi.ipip.net/echo.php
[30/Aug/2019 10:14:12] "GET http://clientapi.ipip.net/echo.php?info=1234567890 HTTP/1.1" 404 1729
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[30/Aug/2019 10:28:18] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1738
=======
>>>>>>> e95ae40b179d3eb696bea3fa8b71b07c9d31d42b
